import random


# -------------------------------
# 🎯 TEMPLATE SELECTION
# -------------------------------
def select_template(prompt: str) -> str:
    prompt = prompt.lower().strip()

    priority_keywords = {
        "template1": [
            "real estate",
            "property",
            "realty",
            "homes",
            "villa",
            "apartment",
            "broker",
        ],
        "template2": [
            "portfolio",
            "developer",
            "designer",
            "resume",
            "personal website",
        ],
        "template3": [
            "agency",
            "marketing",
            "branding",
            "seo",
            "startup",
            "landing",
        ],
        "template4": [
            "ecommerce",
            "shop",
            "store",
            "product",
            "fashion",
            "cart",
        ],
        "template5": [
            "app",
            "mobile",
            "ios",
            "android",
            "software",
            "ai tool",
            "saas",
        ],
        "template6": [
            "blog",
            "writer",
            "content",
            "news",
            "magazine",
        ],
    }

    scores = {}

    for template, words in priority_keywords.items():
        score = sum(1 for word in words if word in prompt)
        scores[template] = score

    best_score = max(scores.values())

    # ✅ choose best matched template
    if best_score > 0:
        winners = [t for t, s in scores.items() if s == best_score]
        return random.choice(winners)

    # 🎲 random fallback
    return random.choice(list(priority_keywords.keys()))


# -------------------------------
# 🔥 MAIN FUNCTION
# -------------------------------
def run_builder(prompt: str):
    template = select_template(prompt)

    return {
        "template": template,
        "content": {
            "heroTitle": prompt.title(),
            "heroSubtitle": "Generated by ClyraUI AI",
        },
    }


# -------------------------------
# ▶️ TEST RUN
# -------------------------------
if __name__ == "__main__":
    user_prompt = input("Enter your website idea: ")
    result = run_builder(user_prompt)

    print("🎯 Selected Template:", result["template"])
    print("📦 Response:", result)