import re


# -------------------------------
# 🔧 DEFAULT DATA
# -------------------------------
def get_default_data():
    return {
        "business_name": "Your Business",
        "hero_title": "Welcome",
        "hero_subtitle": "Generated by ClyraUI",
        "about_text": "We provide amazing services.",
        "services": ["Service 1", "Service 2"],
        "phone": "+91 9876543210",
        "email": "info@example.com",
        "address": "India",
        "year": "2026",
        "hero_image": "https://source.unsplash.com/1200x600/?business",
        "primary_color": "#6366F1",
        "secondary_color": "#06B6D4",
        "text_color": "#111111"
    }


# -------------------------------
# 🔄 MERGE DATA
# -------------------------------
def merge_data(user_data):
    default = get_default_data()

    if not user_data:
        return default

    for key, value in default.items():
        if key not in user_data or not user_data[key]:
            user_data[key] = value

    return user_data


# -------------------------------
# 🧠 NORMALIZE AI CONTENT
# -------------------------------
def normalize_content(data):
    data = merge_data(data)

    if "heading" in data and "hero_title" not in data:
        data["hero_title"] = data["heading"]

    if "description" in data and "hero_subtitle" not in data:
        data["hero_subtitle"] = data["description"]

    if "featuresDescription" in data and "about_text" not in data:
        data["about_text"] = data["featuresDescription"]

    if "logoText" in data and "business_name" not in data:
        data["business_name"] = data["logoText"]

    services_val = data.get("services", [])

    if isinstance(services_val, str):
        data["services"] = [
            s.strip()
            for s in re.split(r"[,\n\r]+", services_val)
            if s.strip()
        ]

    return data


# -------------------------------
# 🎯 SECTION ID HELPER
# -------------------------------
def get_section_ids():
    return {
        "Hero": "hero",
        "AboutSection": "about",
        "ServicesSection": "services",
        "ContactSection": "contact",
        "Footer": "footer"
    }